config/routes.rb
Rails.application.routes.draw do
  get 'session/new'

 # get 'users/new'

  root 'static_page#home'

  get "help" => 'static_page#help'

  get "about"=>'static_page#about'

  get "signup" => "users#new"	
  
  get "login" =>"session#new"
  
  post "login" =>"session#create"
  
  delete "logout" =>"session#destroy"
	
	resources:users

  resources:blogs 
 
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user 
  validates :user_id, presence: true
  #validates :title ,presence: true
  validates :content ,presence: true
  default_scope -> {order(created_at: :desc)}

  
end

app/models/user.rb
class User < ActiveRecord::Base
attr_accessor:remember_token
has_many :blogs , dependent: :destroy
has_attached_file :image,  default_url: "/images/:style/missing.png"
validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
before_save{self.email=email.downcase}
validates :name ,presence:true ,length:{maximum:52}
REGEXa=/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email,presence:true,length:{maximum:255}, format:{with:REGEXa},uniqueness:{case_sensitive:false}
has_secure_password
validates :password ,length:{minimum:6},allow_blank:true

	def User.digest(string)
	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
	BCrypt::Engine.cost
	BCrypt::Password.create(string, cost: cost)
	end


def feed
	Blog.where("user_id = ?", id) # '?' used to preven sql injection attacks
end
	def User.new_token
	SecureRandom.urlsafe_base64
	end
	
	
	def remember
	self.remember_token=User.new_token
	update_attribute(:remember_digest,User.digest(remember_token))
	end
	
	def authenticated?(remember_token)
	return false if remember_digest.nil?
	BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end
	
	def forget
	update_attribute(:remember_digest, nil)
	end
	
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionHelper

  def logged_in_user
    if !logged_in?
      flash[:danger]="Please Log in"
      redirect_to root_url
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

before_action :logged_in_user, only: [:create, :destroy]
	before_action :correct_user, only: :destroy

	def create
		@blog=current_user.blogs.build(blogs_params)
		if @blog.save
			flash[:success] = "Blog created!"
			redirect_to root_url
		else
			render 'static_page/home'
		end
	end


	def edit
		@blog=current_user.blogs.find_by(id:params[:id])
	end

	

	def destroy
		@blog.destroy
	flash[:success] = "Blog deleted"
redirect_to request.referrer || root_url
	end


def update
		@user=current_user
		@blog=@user.blogs.find_by(id:params[:id])
		if @blog.update_attributes(blogs_params)
			flash[:success] = "Blog updated"
redirect_to root_url

		else
			flash[:danger] = "Updating failed"
			redirect_to root_url
		end
	end



def correct_user
@blog = current_user.blogs.find_by(id: params[:id])
redirect_to root_url if @blog.nil?
end




	 

  private

  def blogs_params
  params.require(:blog).permit(:title,:content)
  end

  def logged_in_user
    if !logged_in?
      flash[:danger]="Please Log in"
      redirect_to root_url
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end
  
  def create
  user=User.find_by(email: params[:session][:email])
  if user && user.authenticate(params[:session][:password])
 	log_in user
 	remember user
 	redirect_to user
  else
  flash.now[:danger]="Invalid Details"
  render 'new'
  end
  end
  
  def destroy
	log_out if logged_in?
	
	redirect_to root_url
	end
  
  
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  	if logged_in?
  	@blog = current_user.blogs.build if logged_in?
  	@feed_items = current_user.feed.paginate(page: params[:page])
  end
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
before_action :admin_user, only: :destroy
before_action :logged_in_user, only: [:edit,:update] 
before_action :correct_user, only: [:edit,:update]



	def show
	@user=User.find(params[:id])
	@blogs = @user.blogs
	end 
 
 
  def new
  @user=User.new
  end
  
  def create
  @user=User.new(user_params)
  if @user.save
  name=@user.name
  flash[:success]="Welcome #{name}";
  log_in @user
  redirect_to @user
  else
  render 'new'
  end
  end
  

  def edit
  	@user=User.find(params[:id])

  end

  def update
    @user=User.find(params[:id])
      @blogs=@user.blogs
      if  @user.update_attributes(user_params)
          flash.now[:success]="Profile Updated"
          

          render 'show'
      else

      render 'edit'
      end
    
    
  end

  def destroy
    @user=User.find(params[:id]).destroy
    flash[:success]="#{@user.name} Deleted"
    redirect_to users_url
  end

  def index
    @users=User.all
  end
  private
  
  def user_params
  params.require(:user).permit(:name,:email,:password,:password_confirmation,:image)
  end

  

  
  def admin_user

    if current_user.nil?
      flash[:danger]="Please Log in"
      redirect_to root_url
      
    
  else
    if current_user.admin?
      current_user
    else
      flash[:danger]="Not an admin"
      redirect_to root_url
    end
  end
  end


  def logged_in_user
    if !logged_in?
      flash[:danger]="Please Log in"
      redirect_to root_url
    end
  end


  def correct_user
    @id_access=params[:id].to_i
    @id_curr=current_user.id

    if @id_access != @id_curr
      flash[:danger]="Access Restricted"
      redirect_to root_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


def new_meth(page_title)
base_title="Ruby on Rails"

if page_title.empty?
base_title
else
"#{page_title} | #{base_title}"
end
end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/session_helper.rb
module SessionHelper

	def log_in(user)
	session[:user_id]=user.id
	end
	
	def current_user
	
		if session[:user_id]
		@current_user ||= User.find_by(id: session[:user_id])
		elsif cookies.signed[:user_id]
		@current_user = User.find_by(id: cookies.signed[:user_id])
			if @current_user.authenticated?(cookies[:token_digest])
			@current_user
			end
			
		end
		
	end
	
	def logged_in?
	!current_user.nil?
	end
	
	def log_out
	forget(current_user)
		session.delete(:user_id)
		
		@current_user = nil
	end
	
	def remember (user)
	user.remember
	cookies.permanent.signed[:user_id]=user.id
	cookies.permanent[:token_digest]=user.remember_token
	end
	
	def forget(user)
  user.forget
  cookies.delete(:user_id)
  cookies.delete(:remember_token)
  end
	
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper

def get_avatar(user)
gravid=Digest::MD5::hexdigest(user.email)
ret_url="https://secure.gravatar.com/avatar/#{gravid}"

image_tag(ret_url,alt:user.name,class:"gravatar")
end
end

app/views/blogs/_blog.html.erb
<li id="blog-<%= blog.id %>">

<%if blog.user.image %>
	<%= image_tag(blog.user.image.url,size: "40x40")%>
	<% end %>
<span class="user"><%= link_to blog.user.name, blog.user %></span>

<h2 class="content">Title:<%=blog.title%></h2>
<span class="content"><%= blog.content %></span>
<span class="timestamp">
Posted on <%=blog.created_at %> .
<% if current_user==blog.user %>
<%= link_to "delete", blog, method: :delete,
data: { confirm: "You sure?" } %>
<%= link_to "edit", edit_blog_path(blog),method:"get",
data: { confirm: "You sure?" } %>
<% end %>
</span>
</li>

app/views/blogs/edit.html.erb
<%= form_for(@blog) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
<%=f.label :title%>
<%=f.text_field :title %>
<%= f.text_area :content, placeholder: "Compose new blog..." ,class: 'form-control'%>
</div>
<%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
<%= link_to "sample app", root_path, id: "logo" %>
<nav>
<ul class="nav navbar-nav navbar-right">
<li><%= link_to "Home", root_path %></li>
<li><%= link_to "Help", help_path %></li>
<% if logged_in? %>
<li><%= link_to "Users", users_path, method:"get" %></li>
<li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown">
Account <b class="caret"></b>
</a>
<ul class="dropdown-menu">
<li><%= link_to "Profile", current_user %></li>
<li><%= link_to "Settings", edit_user_path(current_user), method: "get" %></li>
<li class="divider"></li>
<li>
<%= link_to "Log out", logout_path, method: "delete" %>
</li>
</ul>
</li>
<% else %>
<li><%= link_to "Log in", login_path %></li>
<% end %>
</ul>
</nav>
</div>
</header> 

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= new_meth(yield(:title)) %></title>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<%= render('layouts/shim')%>
</head>
<body>
<%= render('layouts/header')%>
<div class="container">
<% flash.each do |message_type,message|%>
<div class="alert alert-<%=message_type%>"><%=message%>
	<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
</div>

<%end%>
<%= yield %>
<%= render('layouts/footer')%>
<%=debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/session/new.html.erb
<% provide(:title, "Log in") %>
<h1>Log in</h1>
<div class="row">
<div class="col-md-6 col-md-offset-3">


<%= form_for(:session, url: login_path) do |f| %>
<%= f.label :email %>
<%= f.email_field :email, class: 'form-control' %>
<%= f.label :password %>
<%= f.password_field :password, class: 'form-control' %>
<%= f.submit "Log in", class: "btn btn-primary" %>
<% end %>
<p>New user? <%= link_to "Sign up now!", signup_path %></p>
</div>
</div>

app/views/shared/_blog_form.html.erb
<%= form_for(@blog) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
<%=f.label :title%>
<%=f.text_field :title %>
<%= f.text_area :content, placeholder: "Compose new blog..." %>
</div>
<%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
<div class="alert alert-danger">
The form contains <%= pluralize(object.errors.count, "error") %>.
</div>
<ul>
<% object.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<ol class="blogs">
<%= render @feed_items %>
</ol>
<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to get_avatar(current_user), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.blogs.count, "blog") %></span>

app/views/static_page/about.html.erb
<%= provide(:title,"About") %>
<h1>hello bitch</h1>

app/views/static_page/help.html.erb
<%= provide(:title,"") %>
<h1>StaticPage#help</h1>
<p>Find me in app/views/static_page/help.html.erb</p>

app/views/static_page/home.html.erb
<%= provide(:title,"Home") %>
<div class="center jumbotron">

<% if logged_in? %>
<div class="row">
<aside class="col-md-4">
<section class="user_info">
<%= render 'shared/user_info' %>
</section>
<section class="blog_form">
<%= render 'shared/blog_form' %>
</section>
</aside>
<div class="col-md-8">
<h3>Blog Feed</h3>
<%= render 'shared/feed' %>
</div>
</div>
<% else %>

<h1>Welcome to the Sample App</h1>
<h2>
This is the home page 
</h2>
<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("Ruby_on_Rails-logo.png", alt: "Rails logo"), 'https://rubyonrails.org/' %>
<%end%>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>
<div class="row">
<div class="col-md-6 col-md-offset-3">


<%= form_for @user  ,html: { multipart: true } do |f| %>
<% @curr=current_user %>

<%= render 'shared/error_messages',object: f.object %>
<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' ,value:"#{@curr.name}" %>
<%= f.label :email %>
<%= f.email_field :email, class: 'form-control' ,value:"#{@curr.email}" %>
<%= f.label :password %>
<%= f.password_field :password, class: 'form-control' %>
<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation, class: 'form-control' %>

<%= f.file_field :image ,value:"/Desktop/app3/rubyapp3-master/app/assets/images/#{@curr.image_file_name}"%>

<%= f.submit "Save changes", class: "btn btn-primary" %>
<% end %>
 <!--<div class="gravatar_edit"> 
<%= get_avatar @user %>
 <a href="http://gravatar.com/emails" target=_blank>change</a>
</div>-->
</div>
</div> 

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<ul class="users">
	<% @users.each do |u|%>

	<li><%= get_avatar u %>
	<%= link_to u.name, user_path(u) %> 
	<%= link_to "Delete",user_path(u),method:"delete"%>
</li>
	<%end%>
</ul>

app/views/users/new.html.erb
<%=provide(:title,"Sign Up")%>
<div class="row">
<div class="col-md-6 col-md-offset-3">
<%= form_for(@user) do |f| %>
<%=render 'shared/error_messages',object: f.object %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :email %>
<%= f.email_field :email %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation %>
<%= f.submit "Create my account", class: "btn btn-primary" %>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
<aside class="col-md-4">
<section class="user_info">
<h1>
	<%if @user.image %>
	<%= image_tag(@user.image.url,size: "80x80")%>
	<% end %>
<%= get_avatar (@user) %>
<%= @user.name %>

</h1>
</section>
</aside>
<div class="col-md-8">
	<% if @user.blogs.any? %>
	<h3>Blogs (<%= @user.blogs.count %>)</h3>
		<ol class="blogs">
		<%= render @blogs %>
		</ol>
	
	<% end %>
</div>
</div>